Enhance Documentation with README.md for Builder and Robot Docker Images
askb/releng-docker pull request #4
Opened 2023-09-05 04:42 UTC by ayushishu

This README.md documentation will help users better understand and utilize our Builder and Robot Docker images.

2023-09-05 07:24 UTC, askb commented on Builder/README.md
> +
PS remove the extra blank lines

2023-09-05 07:25 UTC, askb commented on Builder/README.md
> +This Docker image is designed for building OpenDaylight projects. It provides a pre-configured environment for Maven (MVN) builds on both Ubuntu and CentOS bases.
PS mention if you'll be building the project itself or just running the tests?

2023-09-05 13:01 UTC, ayushishu commented
Update README.md for Builder

2023-09-05 22:59 UTC, askb requested changes

2023-09-05 22:59 UTC, askb commented on Robot/dockerfile
> +# Download, compile,a and install Python 3.10.2
typo remove 'a '

2023-09-06 06:51 UTC, ayushishu commented
Remove the typo mistake

2023-09-06 22:17 UTC, askb approved these changes
LGTM

2023-09-06 22:18 UTC, merged